# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "floppy" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c0878296-7d93-4e1c-84b4-603e2dd8c0db";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/90283667-b0f8-4a37-af6d-ed9461f00d1a"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
