[language-server.clangd]
command = "clangd"
args = [
  "--query-driver=**/arm-none-eabi-*",
  "--background-index",
  "--header-insertion=never",
  "--completion-style=detailed",
]

[[language]]
name = "c"
file-types = ["c", "h"]
auto-format = true
indent = { tab-width = 4, unit = "    " }
